package org.sunbird.exception.message;

/**
 * @author Amit Kumar
 */
public interface IUserResponseMessage {

    String UNAUTHORIZED_USER = "UNAUTHORIZED_USER";
    String RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
    String INVALID_REQUEST_TIMEOUT = "INVALID_REQUEST_TIMEOUT";
    String INVALID_REQUESTED_DATA = "INVALID_REQUESTED_DATA";
    String INVALID_OPERATION_NAME = "INVALID_OPERATION_NAME";
    String INTERNAL_ERROR = "INTERNAL_ERROR";
    String OPERATION_TIMEOUT = "PROCESS_EXE_TIMEOUT";

}
